version: "3.5"

services:
  database:
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=PROD
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d PROD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

volumes:
  database:
  node_modules:
